{{- if and .Values.persistence.enabled .Values.persistence.drupalthemes.hostPath (not .Values.persistence.drupalthemes.existingClaim) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "drupal.fullname" . }}-drupalthemes
spec:
  accessModes:
    - {{ .Values.persistence.drupalthemes.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.drupalthemes.size | quote }}
  hostPath:
   path: {{ .Values.persistence.drupalthemes.hostPath | quote }}
{{- end -}}
