apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drupal.fullname" . }}
  labels:
    app: {{ template "drupal.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.drupalPassword }}
  drupal-password: {{ .Values.drupalPassword | b64enc | quote }}
  {{ else }}
  drupal-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.DRUPALDBPASS }}
  #  DRUPALDBPASS: {{ .Values.DRUPALDBPASS | b64enc | quote }}
  #{{ else }}
  #DRUPALDBPASS: {{ randAlphaNum 10 | b64enc | quote }}
  #{{ end }}
  #{{ if .Values.DRUPALDBUSER }}
  #DRUPALDBUSER: {{ .Values.DRUPALDBUSER | b64enc | quote }}
  #{{ else }}
  #DRUPALDBUSER: {{ randAlphaNum 10 | b64enc | quote }}
  #{{ end }}
  #{{ if .Values.DRUPALDBHOST }}
  #DRUPALDBHOST: {{ .Values.DRUPALDBHOST | b64enc | quote }}
  #{{ else }}
  #DRUPALDBHOST: {{ randAlphaNum 10 | b64enc | quote }}
  #{{ end }}
  #{{ if .Values.DRUPALSALT }}
  DRUPALSALT: {{ .Values.DRUPALSALT | b64enc | quote }}
  {{ else }}
  DRUPALSALT: {{ randAlphaNum 35 | b64enc | quote }}
  {{ end }}
